"""Editor Agent — core "brain" of the tool-use architecture.

The EditorAgent uses ToolUseLoop + StorageTools to:
  1. Analyze a topic against article storage (Phase 1: Analysis)
  2. Generate article proposals based on analysis (Phase 2: Proposals)
  3. Validate proposals (DOI check, duplicate detection, confidence scoring)

Data flow:
    User topic → ToolUseLoop(Analysis) → StorageAnalysis
              → ToolUseLoop(Proposals) → raw proposals
              → Post-validation → ArticleProposal[]
              → EditorResult

State management:
    Each run creates a job with checkpoints saved to /app/data/jobs/
    Supports resume from any completed or in-progress phase.
"""

from __future__ import annotations

import json
import logging
import time
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from engine.llm.tool_loop import ToolUseLoop, ToolUseResult
from engine.llm.response_parser import parse_proposals_from_text
from engine.prompts.editor_prompts import (
    ANALYSIS_SYSTEM_PROMPT,
    PROPOSAL_SYSTEM_PROMPT,
    get_prompt_for_phase,
)
from engine.tools.storage_tools import create_storage_tools
from engine.tools.graph_tools import create_graph_tools

logger = logging.getLogger(__name__)


# ── Data Models ───────────────────────────────────────────────────

@dataclass
class ArticleProposal:
    """A single article proposal generated by the Editor Agent."""
    id: str = ""
    title: str = ""
    thesis: str = ""
    target_audience: str = "general_public"
    confidence: float = 0.5
    sources_available: int = 0
    sources_needed: int = 5
    key_references: list[str] = field(default_factory=list)
    gap_filled: str = ""
    estimated_sections: list[str] = field(default_factory=list)
    status: str = "proposed"  # proposed | selected | duplicate | rejected

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class StorageAnalysis:
    """Results of Phase 1 storage analysis."""
    total_articles: int = 0
    relevant_count: int = 0
    clusters: list[dict] = field(default_factory=list)
    year_range: tuple[int, int] = (0, 0)
    by_year: dict[int, int] = field(default_factory=dict)
    source_distribution: dict[str, int] = field(default_factory=dict)
    existing_articles: list[dict] = field(default_factory=list)
    gaps: list[str] = field(default_factory=list)
    raw_llm_analysis: str = ""

    def to_dict(self) -> dict:
        d = asdict(self)
        d["year_range"] = list(self.year_range)
        return d


@dataclass
class EditorResult:
    """Final result of EditorAgent.run()."""
    job_id: str = ""
    topic: str = ""
    status: str = "pending"  # done | partial | failed
    analysis: StorageAnalysis | None = None
    proposals: list[ArticleProposal] = field(default_factory=list)
    tool_rounds_total: int = 0
    total_tokens_used: int = 0
    duration_sec: float = 0.0
    warnings: list[str] = field(default_factory=list)
    error: str | None = None

    def to_dict(self) -> dict:
        return {
            "job_id": self.job_id,
            "topic": self.topic,
            "status": self.status,
            "analysis": self.analysis.to_dict() if self.analysis else None,
            "proposals": [p.to_dict() for p in self.proposals],
            "tool_rounds_total": self.tool_rounds_total,
            "total_tokens_used": self.total_tokens_used,
            "duration_sec": round(self.duration_sec, 2),
            "warnings": self.warnings,
            "error": self.error,
        }


@dataclass
class EditorState:
    """Checkpoint state for resume capability."""
    job_id: str = ""
    topic: str = ""
    domain: str | None = None
    phase: str = "idle"  # idle | analyzing | proposing | developing | done | failed
    analysis: dict | None = None
    proposals: list[dict] | None = None
    selected_proposal_id: str | None = None
    development_history: list[dict] = field(default_factory=list)
    error: str | None = None
    started_at: str = ""
    updated_at: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


# ── EditorAgent ───────────────────────────────────────────────────

class EditorAgent:
    """
    Main editor agent with tool-use architecture.

    Orchestrates the full analysis → proposal → validation pipeline
    using LLM function calling to query article storage.
    """

    def __init__(self, storage=None, llm=None, jobs_dir: str | Path = "/app/data/jobs"):
        """
        Args:
            storage: JsonlStorage instance (or mock for testing)
            llm: LLMProvider instance with tool_complete() support
            jobs_dir: Directory for checkpoint files
        """
        self.storage = storage
        self.llm = llm
        self.jobs_dir = Path(jobs_dir)
        self.jobs_dir.mkdir(parents=True, exist_ok=True)

        # Lazy init — tools created on first use or explicitly
        self._tools = None
        self._loop = None

    @property
    def tools(self):
        if self._tools is None and self.storage is not None:
            self._tools = create_storage_tools(self.storage)
            # Merge graph tools into the same registry (14 tools total)
            try:
                graph_reg = create_graph_tools()
                for name in graph_reg.list_tools():
                    schema = graph_reg.get_schema(name)
                    handler = graph_reg.get(name)
                    self._tools.register(
                        name=name,
                        handler=handler,
                        description=schema.get("description", ""),
                        **schema.get("input_schema", {}),
                    )
            except Exception:
                pass  # Graph may not exist yet — storage-only mode
        return self._tools

    @property
    def loop(self):
        if self._loop is None and self.llm is not None and self.tools is not None:
            self._loop = ToolUseLoop(self.llm, self.tools)
        return self._loop

    # ── Public API ────────────────────────────────────────────────

    def run(
        self,
        topic: str,
        domain: str | None = None,
        user_instruction: str | None = None,
        max_proposals: int = 5,
        temperature_analysis: float = 0.1,
        temperature_proposal: float = 0.25,
    ) -> EditorResult:
        """
        Main method: analyze topic + generate article proposals.

        Args:
            topic: Topic to analyze (e.g., "Arctic permafrost methane emissions")
            domain: Broader domain context (optional)
            user_instruction: Additional user instructions (optional)
            max_proposals: Maximum number of proposals to generate
            temperature_analysis: LLM temperature for analysis phase (lower = more factual)
            temperature_proposal: LLM temperature for proposal phase

        Returns:
            EditorResult with analysis and validated proposals
        """
        t0 = time.monotonic()

        # Validate prerequisites
        if self.loop is None:
            raise RuntimeError("EditorAgent not initialized: need storage and llm")

        state = EditorState(
            job_id=self._gen_job_id(),
            topic=topic,
            domain=domain,
            phase="analyzing",
            started_at=_now_iso(),
            updated_at=_now_iso(),
        )

        try:
            # ═══ Phase 1: Analysis ═══
            logger.info("[editor] %s Phase 1: Анализ хранилища...", state.job_id)

            user_msg = f"Проанализируй тему '{topic}'"
            if domain:
                user_msg += f" (домен: {domain})"
            if user_instruction:
                user_msg += f"\nДополнительно: {user_instruction}"

            analysis_result: ToolUseResult = self.loop.run(
                user_message=user_msg,
                system_prompt=ANALYSIS_SYSTEM_PROMPT,
                temperature=temperature_analysis,
                max_tokens=2048,
            )

            analysis = self._build_analysis(analysis_result)
            state.analysis = analysis.to_dict()
            state.phase = "proposing"
            state.updated_at = _now_iso()
            self._save_checkpoint(state)

            logger.info(
                "[editor] %s Phase 1 done: %d relevant, %d clusters, %d gaps",
                state.job_id, analysis.relevant_count,
                len(analysis.clusters), len(analysis.gaps),
            )

            # ═══ Phase 2: Proposals ═══
            logger.info("[editor] %s Phase 2: Генерация предложений...", state.job_id)

            context = self._format_analysis_context(analysis)
            proposal_prompt = self._build_proposal_prompt(
                context, max_proposals, topic, domain
            )

            proposal_result: ToolUseResult = self.loop.run(
                user_message=f"Предложи {max_proposals} вариантов статей на русском языке.",
                system_prompt=proposal_prompt,
                temperature=temperature_proposal,
                max_tokens=4096,
            )

            raw_proposals = parse_proposals_from_text(proposal_result.content)

            # Post-validate each proposal
            validated: list[ArticleProposal] = []
            for i, rp in enumerate(raw_proposals):
                vp = self._validate_proposal(rp, analysis, index=i)
                validated.append(vp)

            # Sort by confidence descending
            validated.sort(key=lambda p: p.confidence, reverse=True)

            state.proposals = [p.to_dict() for p in validated]
            state.phase = "done"
            state.updated_at = _now_iso()
            self._save_checkpoint(state)

            elapsed = time.monotonic() - t0

            result = EditorResult(
                job_id=state.job_id,
                topic=topic,
                status="done",
                analysis=analysis,
                proposals=validated,
                tool_rounds_total=analysis_result.total_rounds + proposal_result.total_rounds,
                total_tokens_used=(
                    analysis_result.usage.get("input_tokens", 0) +
                    proposal_result.usage.get("input_tokens", 0)
                ),
                duration_sec=elapsed,
                warnings=analysis_result.warnings + proposal_result.warnings,
                error=None,
            )

            logger.info(
                "[editor] %s Done: %d proposals in %.1fs",
                state.job_id, len(validated), elapsed,
            )
            return result

        except Exception as e:
            logger.error("[editor] %s Error: %s", getattr(state, 'job_id', '?'), e)
            state.phase = "failed"
            state.error = str(e)
            state.updated_at = _now_iso()
            try:
                self._save_checkpoint(state)
            except Exception:
                pass
            raise

    def resume(self, job_id: str) -> EditorResult:
        """Resume a previously completed or failed job."""
        state_path = self.jobs_dir / f"{job_id}.json"

        if not state_path.exists():
            raise ValueError(f"Job {job_id} not found (no checkpoint at {state_path})")

        with open(state_path, "r", encoding="utf-8") as f:
            state_data = json.load(f)

        phase = state_data.get("phase", "unknown")

        if phase == "done":
            return self._reconstruct_result(state_data)

        if phase == "failed":
            return EditorResult(
                job_id=job_id,
                topic=state_data.get("topic", ""),
                status="failed",
                error=state_data.get("error", "Unknown failure"),
            )

        # For in-progress phases, we'd need to resume the loop
        # This is a simplified version — full resume needs message history
        raise ValueError(
            f"Cannot resume from phase '{phase}'. "
            f"Only 'done' and 'failed' phases support resume."
        )

    # ── Private methods ───────────────────────────────────────────

    @staticmethod
    def _build_analysis(loop_result: ToolUseResult) -> StorageAnalysis:
        """Build StorageAnalysis from tool-use loop results."""
        cluster_data = None
        stats_data = None
        search_results = []
        existing_data = None
        explore_data = None

        for tc in loop_result.tool_calls_made:
            name = tc.get("name", "")
            result = tc.get("result", {})

            if name == "cluster_by_subtopic":
                cluster_data = result
            elif name == "count_storage_stats":
                stats_data = result
            elif name == "search_articles":
                search_results.append(result)
            elif name == "find_similar_existing":
                existing_data = result
            elif name == "explore_domain":
                explore_data = result

        # Extract gaps from LLM text response
        gaps = EditorAgent._extract_gaps(loop_result.content)

        # Build year range from stats or explore
        year_range = (0, 0)
        by_year = {}
        total_articles = 0

        if explore_data:
            yr = explore_data.get("year_distribution", {})
            if yr:
                years = [int(y) for y in yr.keys() if str(y).isdigit()]
                year_range = (min(years), max(years)) if years else (0, 0)
                by_year = {int(y): c for y, c in yr.items() if str(y).isdigit()}
            total_articles = explore_data.get("total_in_scope", 0)
        elif stats_data:
            year_range = (
                stats_data.get("min_year", 0),
                stats_data.get("max_year", 0),
            )
            by_year = {
                int(y): c for y, c in stats_data.get("by_year", {}).items()
                if str(y).isdigit()
            }
            total_articles = stats_data.get("total_articles", 0)

        # Source distribution
        source_dist = {}
        if explore_data:
            source_dist = explore_data.get("sources", {})

        # Existing articles
        existing_articles = []
        if existing_data:
            existing_articles = existing_data.get("matches", [])

        return StorageAnalysis(
            total_articles=total_articles,
            relevant_count=sum(sr.get("total_found", 0) for sr in search_results),
            clusters=cluster_data.get("clusters", []) if cluster_data else [],
            year_range=year_range,
            by_year=by_year,
            source_distribution=source_dist,
            existing_articles=existing_articles,
            gaps=gaps,
            raw_llm_analysis=loop_result.content,
        )

    def _validate_proposal(
        self, raw: dict, analysis: StorageAnalysis, index: int = 0
    ) -> ArticleProposal:
        """Validate a raw proposal: DOI check, duplicate check, confidence scoring."""
        # 1. Validate DOIs against storage
        valid_refs = []
        for ref in raw.get("key_references", []):
            doi = ref.replace("DOI:", "").replace("doi:", "").strip()
            if doi and self._check_doi_exists(doi):
                valid_refs.append(ref)

        # 2. Check for duplicates against existing articles
        is_duplicate = False
        title = raw.get("title", "")
        if title and analysis.existing_articles:
            for ex in analysis.existing_articles:
                ex_title = ex.get("preview", "") or ex.get("file", "")
                sim = self._similarity(title.lower(), ex_title.lower())
                if sim > 0.6:
                    is_duplicate = True
                    break

        # 3. Score confidence based on evidence
        base_confidence = float(raw.get("confidence", 0.5))

        # Penalty for few sources
        if len(valid_refs) < 3:
            base_confidence *= 0.7
        elif len(valid_refs) < 5:
            base_confidence *= 0.85

        # Penalty for duplicate
        if is_duplicate:
            base_confidence *= 0.25

        # Clamp to [0, 1]
        base_confidence = max(0.0, min(1.0, base_confidence))

        status = "duplicate" if is_duplicate else "proposed"

        return ArticleProposal(
            id=f"prop_{_now_iso().replace('-','').replace(':','').replace('.','')}_{index}",
            title=raw.get("title", "[без заголовка]"),
            thesis=raw.get("thesis", "[без тезиса]"),
            target_audience=raw.get("target_audience", "general_public"),
            confidence=base_confidence,
            sources_available=len(valid_refs),
            sources_needed=int(raw.get("sources_needed", 5)),
            key_references=valid_refs,
            gap_filled=raw.get("gap_filled", ""),
            estimated_sections=raw.get("estimated_sections", []),
            status=status,
        )

    def _format_analysis_context(self, analysis: StorageAnalysis) -> str:
        """Format analysis results for inclusion in proposal prompt."""
        parts = [
            f"## Результаты анализа хранилища",
            f"",
            f"- Всего статей в базе: {analysis.total_articles}",
            f"- Релевантных по теме: {analysis.relevant_count}",
            f"- Временной охват: {analysis.year_range[0]}–{analysis.year_range[1]}",
            f"",
        ]

        if analysis.clusters:
            parts.append("### Кластеры по подтемам:")
            for c in analysis.clusters[:10]:
                parts.append(f"  - **{c.get('theme', '?')}**: {c.get('count', 0)} статей")
            parts.append("")

        if analysis.gaps:
            parts.append("### Выявленные информационные пробелы:")
            for g in analysis.gaps[:8]:
                parts.append(f"  - {g}")
            parts.append("")

        if analysis.existing_articles:
            parts.append(f"### Уже существующие статьи ({len(analysis.existing_articles)}):")
            for ex in analysis.existing_articles[:5]:
                fname = ex.get("file", "?")
                sim = ex.get("similarity", "?")
                parts.append(f"  - {fname} (сходство: {sim})")
            parts.append("")

        return "\n".join(parts)

    def _build_proposal_prompt(
        self, analysis_context: str, max_proposals: int, topic: str, domain: str | None
    ) -> str:
        """Build the system prompt for Phase 2 (proposals)."""
        base = PROPOSAL_SYSTEM_PROMPT
        # Insert analysis context after the rules section
        context_section = f"\n\n## ДАННЫЕ АНАЛИЗА ХРАНИЛИЩА\n\n{analysis_context}\n"
        # Append constraints
        constraints = f"\n\n## ОГРАНИЧЕНИЯ\n- Максимум {max_proposals} предложений\n"
        if domain:
            constraints += f"- Домен: {domain}\n"
        constraints += f"- Тема: {topic}\n"
        constraints += "- Отвечай ТОЛЬКО на русском языке\n"

        return base + context_section + constraints

    def _save_checkpoint(self, state: EditorState) -> None:
        """Save state to JSON checkpoint file."""
        path = self.jobs_dir / f"{state.job_id}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(state.to_dict(), f, ensure_ascii=False, indent=2, default=str)
        logger.debug("[editor] Checkpoint saved: %s", path)

    def _reconstruct_result(self, state_data: dict) -> EditorResult:
        """Reconstruct EditorResult from saved checkpoint."""
        analysis = None
        if state_data.get("analysis"):
            ad = state_data["analysis"]
            yr = ad.get("year_range", [0, 0])
            analysis = StorageAnalysis(
                total_articles=ad.get("total_articles", 0),
                relevant_count=ad.get("relevant_count", 0),
                clusters=ad.get("clusters", []),
                year_range=(yr[0], yr[1]) if isinstance(yr, list) else (0, 0),
                by_year={int(k): v for k, v in ad.get("by_year", {}).items() if str(k).isdigit()},
                source_distribution=ad.get("source_distribution", {}),
                existing_articles=ad.get("existing_articles", []),
                gaps=ad.get("gaps", []),
                raw_llm_analysis=ad.get("raw_llm_analysis", ""),
            )

        proposals = []
        for pd in state_data.get("proposals", []):
            proposals.append(ArticleProposal(**pd))

        return EditorResult(
            job_id=state_data["job_id"],
            topic=state_data.get("topic", ""),
            status=state_data.get("phase", "unknown"),
            analysis=analysis,
            proposals=proposals,
            error=state_data.get("error"),
        )

    # ── Helpers ────────────────────────────────────────────────────

    @staticmethod
    def _gen_job_id() -> str:
        """Generate unique job ID based on timestamp."""
        return f"edit_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"

    def _check_doi_exists(self, doi: str) -> bool:
        """Check if DOI exists in storage via validate_doi tool."""
        if self.tools is None:
            return False  # Can't validate without tools
        result = self.tools.execute("validate_doi", {"doi": doi})
        if hasattr(result, 'success'):
            return result.success and result.data.get("valid", False)
        try:
            import json as _j
            d = _j.loads(result) if isinstance(result, str) else result
            return d.get("valid", False)
        except Exception:
            return False

    @staticmethod
    def _extract_gaps(text: str) -> list[str]:
        """Extract information gaps from LLM analysis text."""
        gaps = []
        # Look for patterns like "пробел:", "не хватает:", "gap:", "недостаточно:"
        patterns = [
            r'(?:пробел|не хватает|недостаточно|gap|missing)[^.:]*[:\.]\s*([^\n]+)',
            r'-\s*(?:нет|отсутствует|не покрыто)[^\n]*',
        ]
        import re
        for pattern in patterns:
            for m in re.finditer(pattern, text, re.IGNORECASE):
                gap = m.group(1) if m.lastindex else m.group(0)
                gap = gap.strip().lstrip("- ").strip()
                if len(gap) > 5:
                    gaps.append(gap)
        return gaps[:10]  # Limit to top 10

    @staticmethod
    def _similarity(a: str, b: str) -> float:
        """Simple Jaccard similarity between two strings."""
        if not a or not b:
            return 0.0
        sa = set(a.split())
        sb = set(b.split())
        intersection = sa & sb
        union = sa | sb
        return len(intersection) / len(union) if union else 0.0


def _now_iso() -> str:
    """Current UTC time in ISO format."""
    return datetime.now(timezone.utc).isoformat()
