"""Editor Agent — core "brain" of the B+ hybrid architecture.

B+ Architecture (Evidence Pack + LLM Discovery):
  Phase 0: LOADER   (Python)  — load ALL articles + graph → EvidencePack
  Phase 1: DISCOVERY (LLM+tools) — explore data, dig deeper → DiscoveryReport
  Phase 2: SYNTHESIZE (LLM)     — form 1-3 deep proposals based on discovery
  Phase 3: VALIDATE  (Python)   — DOI gate, scoring, enrichment

Data flow:
    User topic → EvidencePack → ToolUseLoop(Discovery) → DiscoveryReport
              → ToolUseLoop(Synthesize) → raw proposals
              → Post-validation → ArticleProposal[]
              → EditorResult

State management:
    Each run creates a job with checkpoints saved to /app/data/jobs/
    Supports resume from completed or failed phases.
"""

from __future__ import annotations

import json
import logging
import time
import uuid
import re
from collections import Counter
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from engine.llm.tool_loop import ToolUseLoop, ToolUseResult
from engine.llm.response_parser import parse_proposals_from_text
from engine.prompts.editor_prompts import (
    DISCOVERY_SYSTEM_PROMPT,
    SYNTHESIZE_SYSTEM_PROMPT,
    get_prompt_for_phase,
)
from engine.tools.storage_tools import create_storage_tools
from engine.tools.graph_tools import create_graph_tools

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────

DISCOVERY_MAX_ROUNDS = 4       # Max LLM rounds in discovery phase
SYNTHESIZE_MAX_ROUNDS = 2      # Max LLM rounds in synthesize phase
ABSTRACT_PREVIEW_LEN = 300     # Chars of abstract in evidence pack
MAX_PROPOSALS_HARD = 3         # Hard cap on proposals (quality > quantity)


# ── Data Models ───────────────────────────────────────────────────

@dataclass
class ArticleProposal:
    """A single article proposal generated by the Editor Agent."""
    id: str = ""
    title: str = ""
    thesis: str = ""
    target_audience: str = "general_public"
    confidence: float = 0.5
    sources_available: int = 0
    sources_needed: int = 5
    key_references: list[str] = field(default_factory=list)
    gap_filled: str = ""
    estimated_sections: list[str] = field(default_factory=list)
    status: str = "proposed"  # proposed | selected | duplicate | rejected
    # B+ enrichment fields
    enriched_sources: list[dict] = field(default_factory=list)
    graph_roles: dict = field(default_factory=dict)
    discovery_depth: str = "shallow"  # shallow | medium | deep

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class EvidencePack:
    """Phase 0 output: all data loaded without filtering.
    Python builds this in ~2 seconds. No LLM involved."""
    all_articles: list[dict] = field(default_factory=list)
    total_articles: int = 0
    graph_summary: dict = field(default_factory=dict)
    domain_stats: dict = field(default_factory=dict)
    graph_available: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class DiscoveryReport:
    """Phase 1 output: LLM's research findings after exploring evidence pack."""
    key_findings: str = ""
    selected_dois: list[str] = field(default_factory=list)
    explored_dois: list[str] = field(default_factory=list)
    cross_connections: list[dict] = field(default_factory=list)
    additional_queries: list[str] = field(default_factory=list)
    gap_hypotheses: list[str] = field(default_factory=list)
    material_sufficiency: str = "unknown"  # sufficient | limited | insufficient
    confidence_note: str = ""
    raw_llm_discovery: str = ""

    def to_dict(self) -> dict:
        return asdict(self)

    @property
    def is_sufficient(self) -> bool:
        return self.material_sufficiency == "sufficient"

    @property
    def proposal_count_hint(self) -> int:
        if self.material_sufficiency == "sufficient":
            return 3
        elif self.material_sufficiency == "limited":
            return 2
        return 1


@dataclass
class EditorResult:
    """Final result of EditorAgent.run()."""
    job_id: str = ""
    topic: str = ""
    status: str = "pending"
    analysis: dict | None = None          # Legacy key — holds DiscoveryReport dict
    discovery: DiscoveryReport | None = None
    proposals: list[ArticleProposal] = field(default_factory=list)
    tool_rounds_total: int = 0
    total_tokens_used: int = 0
    duration_sec: float = 0.0
    warnings: list[str] = field(default_factory=list)
    error: str | None = None

    def to_dict(self) -> dict:
        return {
            "job_id": self.job_id,
            "topic": self.topic,
            "status": self.status,
            "analysis": self.analysis,
            "discovery": self.discovery.to_dict() if self.discovery else None,
            "proposals": [p.to_dict() for p in self.proposals],
            "tool_rounds_total": self.tool_rounds_total,
            "total_tokens_used": self.total_tokens_used,
            "duration_sec": round(self.duration_sec, 2),
            "warnings": self.warnings,
            "error": self.error,
        }


@dataclass
class EditorState:
    """Checkpoint state for resume capability."""
    job_id: str = ""
    topic: str = ""
    domain: str | None = None
    phase: str = "idle"
    # idle | loading | discovering | synthesizing | validating | done | failed
    evidence_pack: dict | None = None
    discovery: dict | None = None
    analysis: dict | None = None   # Legacy alias for discovery
    proposals: list[dict] | None = None
    selected_proposal_id: str | None = None
    development_history: list[dict] = field(default_factory=list)
    error: str | None = None
    started_at: str = ""
    updated_at: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


# ── EditorAgent ───────────────────────────────────────────────────

class EditorAgent:
    """Main editor agent with B+ hybrid architecture.

    Orchestrates: Loader → Discovery(LLM+tools) → Synthesize(LLM) → Validate(Python)
    """

    def __init__(self, storage=None, llm=None, jobs_dir: str | Path = "/app/data/jobs"):
        self.storage = storage
        self.llm = llm
        self.jobs_dir = Path(jobs_dir)
        self.jobs_dir.mkdir(parents=True, exist_ok=True)
        self._tools = None
        self._loop = None

    @property
    def tools(self):
        if self._tools is None and self.storage is not None:
            self._tools = create_storage_tools(self.storage)
            try:
                graph_reg = create_graph_tools()
                for name in graph_reg.list_tools():
                    schema = graph_reg.get_schema(name)
                    handler = graph_reg.get(name)
                    self._tools.register(
                        name=name, handler=handler,
                        description=schema.get("description", ""),
                        **schema.get("input_schema", {}),
                    )
            except Exception as e:
                logger.warning("Graph tools not available: %s", e)
        return self._tools

    @property
    def loop(self):
        if self._loop is None and self.llm is not None and self.tools is not None:
            self._loop = ToolUseLoop(self.llm, self.tools)
        return self._loop

    def _make_loop(self, max_rounds: int = 8) -> ToolUseLoop:
        """Create a ToolUseLoop instance with custom max_rounds."""
        if self.llm is None or self.tools is None:
            raise RuntimeError("EditorAgent not initialized: need storage and llm")
        return ToolUseLoop(self.llm, self.tools, max_rounds=max_rounds)

    # ── Public API ────────────────────────────────────────────────

    def run(
        self,
        topic: str,
        domain: str | None = None,
        user_instruction: str | None = None,
        max_proposals: int = 5,           # legacy param, ignored (B+ decides count)
        temperature_analysis: float = 0.1, # used for discovery phase
        temperature_proposal: float = 0.25,# used for synthesize phase
    ) -> EditorResult:
        """Main method: load evidence → discover → synthesize → validate."""
        t0 = time.monotonic()

        if self.loop is None:
            raise RuntimeError("EditorAgent not initialized: need storage and llm")

        state = EditorState(
            job_id=self._gen_job_id(),
            topic=topic,
            domain=domain,
            phase="loading",
            started_at=_now_iso(),
            updated_at=_now_iso(),
        )
        self._save_checkpoint(state)

        try:
            # ════════════════════════════════════════════
            # PHASE 0: LOADER (Python, ~2 sec)
            # ════════════════════════════════════════════
            logger.info("[editor] %s Phase 0: Loading evidence pack...", state.job_id)
            state.phase = "loading"

            evidence = self._build_evidence_pack(topic)
            state.evidence_pack = evidence.to_dict()
            state.updated_at = _now_iso()
            self._save_checkpoint(state)

            logger.info(
                "[editor] %s Phase 0 done: %d articles, graph=%s",
                state.job_id, evidence.total_articles, evidence.graph_available,
            )

            # ════════════════════════════════════════════
            # PHASE 1: DISCOVERY (LLM + tools, up to 4 rounds)
            # ════════════════════════════════════════════
            logger.info("[editor] %s Phase 1: Discovery...", state.job_id)
            state.phase = "discovering"

            discovery_result = self._run_discovery(
                topic=topic,
                domain=domain,
                user_instruction=user_instruction,
                evidence=evidence,
                temperature=temperature_analysis,
            )
            discovery = self._parse_discovery(discovery_result, evidence)
            state.discovery = discovery.to_dict()
            state.analysis = discovery.to_dict()  # Legacy alias
            state.phase = "synthesizing"
            state.updated_at = _now_iso()
            self._save_checkpoint(state)

            logger.info(
                "[editor] %s Phase 1 done: sufficiency=%s, selected=%d DOIs, explored=%d",
                state.job_id, discovery.material_sufficiency,
                len(discovery.selected_dois), len(discovery.explored_dois),
            )

            # ════════════════════════════════════════════
            # PHASE 2: SYNTHESIZE (LLM, 1-2 rounds)
            # ════════════════════════════════════════════
            logger.info("[editor] %s Phase 2: Synthesizing proposals...", state.job_id)

            synthesize_result = self._run_synthesize(
                topic=topic,
                domain=domain,
                discovery=discovery,
                evidence=evidence,
                temperature=temperature_proposal,
            )
            raw_proposals = parse_proposals_from_text(synthesize_result.content)

            # Critical: warn if synthesize produced nothing
            if not raw_proposals:
                logger.warning(
                    "[editor] %s Synthesize returned 0 proposals! "
                    "content_len=%d, content_preview=%s",
                    state.job_id,
                    len(synthesize_result.content),
                    synthesize_result.content[:300] + ("..." if len(synthesize_result.content) > 300 else "")
                )

            # ════════════════════════════════════════════
            # PHASE 3: VALIDATE (Python, ~1 sec)
            # ════════════════════════════════════════════
            logger.info("[editor] %s Phase 3: Validating %d raw proposals...", state.job_id, len(raw_proposals))
            state.phase = "validating"

            validated: list[ArticleProposal] = []
            for i, rp in enumerate(raw_proposals):
                vp = self._validate_proposal_bplus(rp, discovery, evidence, index=i)
                validated.append(vp)

            # Sort by confidence descending, cap at MAX_PROPOSALS_HARD
            validated.sort(key=lambda p: p.confidence, reverse=True)
            validated = validated[:MAX_PROPOSALS_HARD]

            # Warn if material was insufficient
            warnings = []
            if discovery.material_sufficiency == "insufficient":
                warnings.append(
                    f"Недостаточно материала в базе для темы '{topic}'. "
                    f"Возвращён 1 вариант с пониженным confidence. "
                    f"Рекомендуется пополнить digest перед написанием."
                )
            warnings.extend(synthesize_result.warnings)
            warnings.extend(discovery_result.warnings)

            state.proposals = [p.to_dict() for p in validated]
            state.phase = "done"
            state.updated_at = _now_iso()
            self._save_checkpoint(state)

            elapsed = time.monotonic() - t0
            total_tokens = (
                discovery_result.usage.get("input_tokens", 0)
                + discovery_result.usage.get("output_tokens", 0)
                + synthesize_result.usage.get("input_tokens", 0)
                + synthesize_result.usage.get("output_tokens", 0)
            )

            result = EditorResult(
                job_id=state.job_id,
                topic=topic,
                status="done",
                analysis=discovery.to_dict(),
                discovery=discovery,
                proposals=validated,
                tool_rounds_total=discovery_result.total_rounds + synthesize_result.total_rounds,
                total_tokens_used=total_tokens,
                duration_sec=elapsed,
                warnings=warnings,
                error=None,
            )

            logger.info(
                "[editor] %s Done: %d proposals (%s) in %.1fs, %d tokens, %d rounds",
                state.job_id, len(validated), discovery.material_sufficiency,
                elapsed, total_tokens, result.tool_rounds_total,
            )
            return result

        except Exception as e:
            logger.error("[editor] %s Error: %s", getattr(state, 'job_id', '?'), e)
            state.phase = "failed"
            state.error = str(e)
            state.updated_at = _now_iso()
            try:
                self._save_checkpoint(state)
            except Exception:
                pass
            raise

    # ── Resume ────────────────────────────────────────────────────

    def resume(self, job_id: str) -> EditorResult:
        """Resume a previously completed or failed job."""
        state_path = self.jobs_dir / f"{job_id}.json"
        if not state_path.exists():
            raise ValueError(f"Job {job_id} not found (no checkpoint at {state_path})")

        with open(state_path, "r", encoding="utf-8") as f:
            state_data = json.load(f)

        phase = state_data.get("phase", "unknown")
        if phase == "done":
            return self._reconstruct_result(state_data)
        if phase == "failed":
            return EditorResult(
                job_id=job_id,
                topic=state_data.get("topic", ""),
                status="failed",
                error=state_data.get("error", "Unknown failure"),
            )
        raise ValueError(
            f"Cannot resume from phase '{phase}'. "
            f"Only 'done' and 'failed' phases support resume."
        )

    # ── Phase 0: Loader ───────────────────────────────────────────

    def _build_evidence_pack(self, topic: str = "") -> EvidencePack:
        """Load ALL articles + graph summary without any filtering.
        Pure Python, no LLM. Takes ~2 seconds."""
        articles_raw = []
        if self.storage is not None:
            articles_raw = self.storage.load_articles()

        # Build compact article cards (~200 bytes each)
        all_articles = []
        source_counts: Counter = Counter()
        year_list: list[int] = []
        topics_all: list[str] = []
        enriched_count = 0

        for art in articles_raw:
            doi = art.get("doi", "")
            abstract = art.get("abstract_ru") or art.get("abstract", "") or ""
            card = {
                "doi": doi,
                "title": art.get("title", ""),
                "title_ru": art.get("title_ru", ""),
                "year": art.get("year"),
                "topics_ru": art.get("topics_ru", []) or [],
                "source": art.get("source", ""),
                "abstract_preview": abstract[:ABSTRACT_PREVIEW_LEN],
                "score_total": art.get("scores", {}).get("total_5", 0),
                "citations": art.get("citations", 0),
                "has_summary": bool(art.get("llm_summary")),
            }
            all_articles.append(card)
            source_counts[card["source"]] += 1
            if isinstance(card["year"], int):
                year_list.append(card["year"])
            topics_all.extend(card["topics_ru"])
            if card["has_summary"]:
                enriched_count += 1

        # Domain stats
        top_topics = [t for t, _ in Counter(topics_all).most_common(10)]
        domain_stats = {
            "sources": dict(source_counts.most_common()),
            "years": {
                "min": min(year_list) if year_list else 0,
                "max": max(year_list) if year_list else 0,
            },
            "top_topics_ru": top_topics,
            "enriched_pct": round(enriched_count / len(all_articles) * 100, 1) if all_articles else 0,
        }

        # Graph summary (if available)
        graph_summary = {}
        graph_available = False
        try:
            if self.storage is not None:
                graph_data = self.storage.load_graph()
                nodes = graph_data.get("nodes", [])
                edges = graph_data.get("edges", [])

                if nodes:
                    graph_available = True
                    # Communities
                    communities = {}
                    comm_map: dict[str, str] = {}
                    for n in nodes:
                        d = n.get("data", {})
                        cid = d.get("community", "?")
                        comm_map[d.get("id", "")] = cid
                        if cid not in communities:
                            communities[cid] = {"theme": d.get("label", ""), "count": 0, "sample_dois": []}
                        communities[cid]["count"] += 1
                        if len(communities[cid]["sample_dois"]) < 3:
                            doi = d.get("doi", "")
                            if doi:
                                communities[cid]["sample_dois"].append(doi)

                    # Hubs (top by page_rank)
                    hubs = sorted(
                        [
                            {"doi": n["data"].get("doi", ""), "title_ru": n["data"].get("label", ""),
                             "page_rank": n["data"].get("page_rank", 0)}
                            for n in nodes
                            if n.get("data", {}).get("is_hub")
                        ],
                        key=lambda x: x["page_rank"],
                        reverse=True,
                    )[:10]

                    # Bridges (top by betweenness)
                    bridges = sorted(
                        [
                            {"doi": n["data"].get("doi", ""), "title_ru": n["data"].get("label", ""),
                             "betweenness": n["data"].get("betweenness", 0)}
                            for n in nodes
                            if n.get("data", {}).get("is_bridge")
                        ],
                        key=lambda x: x["betweenness"],
                        reverse=True,
                    )[:10]

                    graph_summary = {
                        "communities": [
                            {"id": k, "theme": v["theme"], "count": v["count"], "sample_dois": v["sample_dois"]}
                            for k, v in sorted(communities.items())
                        ],
                        "hubs": hubs,
                        "bridges": bridges,
                        "node_count": len(nodes),
                        "edge_count": len(edges),
                    }
        except Exception as e:
            logger.debug("Graph summary build skipped: %s", e)

        return EvidencePack(
            all_articles=all_articles,
            total_articles=len(all_articles),
            graph_summary=graph_summary,
            domain_stats=domain_stats,
            graph_available=graph_available,
        )

    # ── Phase 1: Discovery ─────────────────────────────────────────

    def _run_discovery(
        self,
        topic: str,
        domain: str | None,
        user_instruction: str | None,
        evidence: EvidencePack,
        temperature: float,
    ) -> ToolUseResult:
        """Run LLM discovery phase: explore evidence pack with tools."""
        user_msg = f"Исследуй тему '{topic}' на основе предоставленных данных."
        if domain:
            user_msg += f"\nДомен: {domain}"
        if user_instruction:
            user_msg += f"\nДополнительно: {user_instruction}"

        # Inject evidence pack into system prompt
        prompt = DISCOVERY_SYSTEM_PROMPT + "\n\n## EVIDENCE PACK (Phase 0)\n\n"
        prompt += self._format_evidence_for_discovery(evidence)
        prompt += f"\n\nТема исследования: {topic}\n"

        result = self._make_loop(DISCOVERY_MAX_ROUNDS).run(
            user_message=user_msg,
            system_prompt=prompt,
            temperature=temperature,
            max_tokens=4096,
        )
        return result

    def _format_evidence_for_discovery(self, evidence: EvidencePack) -> str:
        """Format evidence pack as compact text for LLM discovery prompt."""
        parts = []

        # Stats line
        ds = evidence.domain_stats
        parts.append(f"**База данных:** {evidence.total_articles} статей, "
                     f"годы {ds['years']['min']}-{ds['years']['max']}, "
                     f"{ds['enriched_pct']}% обогащено LLM-summary.")
        parts.append(f"**Источники:** {ds['sources']}")
        parts.append(f"**Топ темы:** {', '.join(ds['top_topics_ru'][:12])}")
        parts.append("")

        # Article listing (compact — DOI + title_ru + year + topics + preview)
        parts.append("### Все статьи в базе:")
        for i, a in enumerate(evidence.all_articles):
            topics_str = ", ".join(a["topics_ru"][:4]) if a["topics_ru"] else "-"
            parts.append(
                f"  [{i+1}] DOI:{a['doi']} | {a['title_ru'] or a['title']}"
                f" ({a['year']}, {a['source']}) | {topics_str}"
                f" | {a['abstract_preview'][:120]}..."
            )
        parts.append("")

        # Graph summary
        if evidence.graph_available and evidence.graph_summary:
            gs = evidence.graph_summary
            parts.append(f"### Граф знаний: {gs['node_count']} узлов, {gs['edge_count']} рёбер")

            if gs.get("communities"):
                parts.append("**Сообщества:**")
                for c in gs["communities"][:8]:
                    parts.append(f"  - Community {c['id']}: {c['theme']} "
                                 f"({c['count']} статей) — примеры: {', '.join(c['sample_dois'][:3])}")

            if gs.get("hubs"):
                h_names = [h["title_ru"] or h["doi"] for h in gs["hubs"][:6]]
                parts.append(f"**Хабы:** {', '.join(h_names)}")

            if gs.get("bridges"):
                b_names = [b["title_ru"] or b["doi"] for b in gs["bridges"][:6]]
                parts.append(f"**Мосты:** {', '.join(b_names)}")
            parts.append("")
        else:
            parts.append("*Граф знаний недоступен.*\n")

        return "\n".join(parts)

    def _parse_discovery(self, result: ToolUseResult, evidence: EvidencePack) -> DiscoveryReport:
        """Parse LLM discovery output into structured DiscoveryReport."""
        text = result.content or ""

        # Extract selected DOIs from text (look for DOI patterns)
        doi_pattern = r'(?:DOI[:\s]*|doi[:\s]*|10\.\d{4,}/[^\s,\]\)]+)'
        found_dois = re.findall(doi_pattern, text, re.IGNORECASE)
        cleaned_dois = []
        for d in found_dois:
            d = d.replace("DOI:", "").replace("doi:", "").strip()
            if d.startswith("10.") and d not in cleaned_dois:
                cleaned_dois.append(d)

        # Also collect DOIs from get_article_detail tool calls
        explored_dois = []
        for tc in result.tool_calls_made:
            if tc.get("name") == "get_article_detail":
                doi = tc.get("arguments", {}).get("doi", "")
                if doi and doi not in explored_dois:
                    explored_dois.append(doi)
            elif tc.get("name") == "search_articles":
                query = tc.get("arguments", {}).get("query", "")
                # We'll track queries separately

        # Determine material sufficiency from LLM text
        sufficiency = "unknown"
        lower_text = text.lower()
        if any(w in lower_text for w in ["достаточно", "sufficient", "богат", "обширн", "хорошо покрыт"]):
            sufficiency = "sufficient"
        elif any(w in lower_text for w in ["недостаточно", "insufficient", "мало", "ограничен", "слабо"]):
            sufficiency = "limited"
        elif any(w in lower_text for w in ["критически", "практически нет", "почти нет", "очень мало"]):
            sufficiency = "insufficient"
        else:
            # Default heuristic: if we found >= 5 relevant-looking DOIs → sufficient
            if len(cleaned_dois) >= 5 or len(explored_dois) >= 5:
                sufficiency = "sufficient"
            elif len(cleaned_dois) >= 2 or len(explored_dois) >= 2:
                sufficiency = "limited"
            else:
                sufficiency = "insufficient"

        # Merge: selected = union of found in text + explored via tools
        all_found = set(cleaned_dois) | set(explored_dois)

        # Additional queries from search_articles calls
        additional_queries = []
        for tc in result.tool_calls_made:
            if tc.get("name") == "search_articles":
                q = tc.get("arguments", {}).get("query", "")
                if q:
                    additional_queries.append(q)

        # Gap hypotheses
        gaps = self._extract_gaps(text)

        # ── Generate findings text if content was empty (max_rounds bug) ──
        if not text or len(text.strip()) < 20:
            # Build findings from tool call history
            parts = [f"Исследование завершено (анализ {len(result.tool_calls_made)} tool-вызовов)."]
            if all_found:
                parts.append(f"Найдено релевантных статей: {len(all_found)}.")
            if explored_dois:
                parts.append(f"Детально изучено: {len(explored_dois)} статей.")
            if additional_queries:
                parts.append(f"Выполнено поисковых запросов: {len(additional_queries)}.")
            parts.append(f"Оценка материала: {sufficiency}.")
            text = "\n".join(parts)
            logger.info(
                "[editor] Discovery content was empty, generated from %d tool calls",
                len(result.tool_calls_made),
            )

        return DiscoveryReport(
            key_findings=text[:2000],  # Truncate very long findings
            selected_dois=list(all_found),
            explored_dois=explored_dois,
            cross_connections=[],  # Would need deeper parsing
            additional_queries=additional_queries,
            gap_hypotheses=gaps,
            material_sufficiency=sufficiency,
            confidence_note=text[-500:] if len(text) > 500 else "",
            raw_llm_discovery=text,
        )

    # ── Phase 2: Synthesize ─────────────────────────────────────────

    def _run_synthesize(
        self,
        topic: str,
        domain: str | None,
        discovery: DiscoveryReport,
        evidence: EvidencePack,
        temperature: float,
    ) -> ToolUseResult:
        """Run LLM synthesize phase: form proposals based on discovery.

        Uses direct LLM call (no tools) — LLM has all context from discovery report.
        This avoids the 'empty content' bug when ToolUseLoop hits max_rounds.
        """
        hint = discovery.proposal_count_hint

        user_msg = (
            f"На основе своего исследования предложи концепты статей по теме '{topic}'.\n"
            f"Качество >> количество. Предложи от 1 до {hint} вариантов.\n"
            f"Оценка материала: {discovery.material_sufficiency}."
        )

        prompt = SYNTHESIZE_SYSTEM_PROMPT + "\n\n"
        prompt += self._format_synthesis_context(discovery, evidence)
        prompt += f"\n## ОГРАНИЧЕНИЯ\n"
        prompt += f"- Максимум {MAX_PROPOSALS_HARD} вариантов (качество > количества)\n"
        prompt += f"- Материал: {discovery.material_sufficiency} (предложи ~{hint} вариантов)\n"
        if domain:
            prompt += f"- Домен: {domain}\n"
        prompt += f"- Тема: {topic}\n"
        prompt += f"- Используй ТОЛЬКО DOI из списка selected_dois выше\n"
        prompt += f"- Отвечай ТОЛЬКО на русском языке\n"

        # Direct LLM call — no tools, single round, guaranteed text response
        try:
            response = self.llm.complete(
                prompt=user_msg,
                system=prompt,
                temperature=temperature,
                max_tokens=4096,
            )

            # Log raw response for debugging (critical for format issues)
            logger.info(
                "[editor] Synthesize RAW response (%d chars): %s",
                len(str(response)),
                str(response)[:500] + ("..." if len(str(response)) > 500 else "")
            )
            # Handle different response formats
            if isinstance(response, dict):
                content = response.get("content", "")
                if isinstance(content, list):
                    # Content blocks format — extract text
                    parts = []
                    for block in content:
                        if isinstance(block, dict):
                            if block.get("type") == "text":
                                parts.append(block.get("text", ""))
                        elif isinstance(block, str):
                            parts.append(block)
                    content = "\n".join(parts)
                usage = response.get("usage", {})
            elif isinstance(response, str):
                content = response
                usage = {}
            else:
                content = str(response)
                usage = {}

            return ToolUseResult(
                content=content or "",
                tool_calls_made=[],
                total_rounds=1,
                stop_reason="end_turn",
                usage=usage,
            )
        except Exception as e:
            logger.warning("[editor] Synthesize direct call failed, fallback: %s", e)
            # Fallback to ToolUseLoop if direct call fails
            result = self._make_loop(SYNTHESIZE_MAX_ROUNDS).run(
                user_message=user_msg,
                system_prompt=prompt,
                temperature=temperature,
                max_tokens=4096,
            )
            return result

    def _format_synthesis_context(self, discovery: DiscoveryReport, evidence: EvidencePack) -> str:
        """Format discovery report + enriched article details for synthesis prompt."""
        parts = ["## DISCOVERY REPORT (результаты исследования)", ""]

        parts.append(f"### Ключевые находки:")
        parts.append(discovery.key_findings or "(нет находок)")
        parts.append("")

        parts.append(f"### Выбранные статьи ({len(discovery.selected_dois)} DOI):")
        for doi in discovery.selected_dois:
            # Find full article info from evidence pack
            art = next((a for a in evidence.all_articles if a["doi"] == doi), None)
            if art:
                depth_mark = "**[deep]**" if doi in discovery.explored_dois else ""
                parts.append(
                    f"  - DOI:{doi} {depth_mark}\n"
                    f"    {art['title_ru'] or art['title']} ({art['year']}, {art['source']})\n"
                    f"    Topics: {', '.join(art['topics_ru'][:5])}\n"
                    f"    Abstract: {art['abstract_preview'][:200]}"
                )
            else:
                parts.append(f"  - DOI:{doi} (не найдена в evidence pack)")
        parts.append("")

        if discovery.gap_hypotheses:
            parts.append("### Гипотезы о пробелах:")
            for g in discovery.gap_hypotheses[:6]:
                parts.append(f"  - {g}")
            parts.append("")

        if discovery.additional_queries:
            parts.append(f"### Дополнительные запросы: {discovery.additional_queries}")
            parts.append("")

        parts.append(f"### Оценка материала: **{discovery.material_sufficiency}**")
        if discovery.confidence_note:
            parts.append(f"Примечание: {discovery.confidence_note[:300]}")
        parts.append("")

        return "\n".join(parts)

    # ── Phase 3: Validate ──────────────────────────────────────────

    def _validate_proposal_bplus(
        self, raw: dict, discovery: DiscoveryReport, evidence: EvidencePack, index: int = 0
    ) -> ArticleProposal:
        """B+ validation: DOI gate against discovery report + enhanced scoring."""
        raw_refs = raw.get("key_references", [])
        valid_refs = []
        unchecked_refs = []
        valid_in_local = 0

        allowed_dois = set(discovery.selected_dois)

        for ref in raw_refs:
            doi = ref.replace("DOI:", "").replace("doi:", "").strip()
            if not doi:
                continue

            # B+ RULE: DOI must be in discovery's selected_dois OR validate in local DB
            is_allowed = doi in allowed_dois
            is_valid_local = False

            if self.tools is not None:
                try:
                    result = self.tools.execute("validate_doi", {"doi": doi})
                    if hasattr(result, 'success') and result.success and result.data.get("valid"):
                        valid_refs.append(ref)
                        valid_in_local += 1
                        is_valid_local = True
                        continue
                except Exception:
                    pass

            if is_allowed:
                # In discovery but not validated locally → keep as unchecked
                unchecked_refs.append(ref)
            # If NOT in discovery AND NOT local → drop it (wasn't researched)

        key_references = valid_refs if valid_refs else unchecked_refs

        # Duplicate check
        is_duplicate = False
        title = raw.get("title", "")
        # Note: existing_articles check requires find_similar_existing which needs tools
        # For now, skip duplicate check here (it's done at orchestrator level too)

        # Confidence scoring (B+ enhanced)
        base_confidence = float(raw.get("confidence", 0.5))

        # Evidence depth bonus
        refs_with_detail = sum(1 for r in key_references
                               for d in r.replace("DOI:", "").replace("doi:", "").strip().split()
                               if d.startswith("10.") and d in discovery.explored_dois)
        if refs_with_detail >= 5:
            base_confidence *= 1.1   # Deep research bonus
        elif refs_with_detail >= 3:
            base_confidence *= 1.05  # Medium depth

        # Source diversity check
        ref_sources = set()
        for ref in key_references:
            doi_clean = ref.replace("DOI:", "").replace("doi:", "").strip()
            art = next((a for a in evidence.all_articles if a["doi"] == doi_clean), None)
            if art:
                ref_sources.add(art["source"])
        if len(ref_sources) >= 3:
            base_confidence *= 1.05  # Diverse sources bonus

        # Material penalty
        if discovery.material_sufficiency == "insufficient":
            base_confidence *= 0.6
        elif discovery.material_sufficiency == "limited":
            base_confidence *= 0.85

        # Few sources penalty
        total_refs = len(key_references)
        if total_refs < 3:
            base_confidence *= 0.7
        elif total_refs < 5:
            base_confidence *= 0.85

        # Duplicate penalty
        if is_duplicate:
            base_confidence *= 0.25

        base_confidence = max(0.0, min(1.0, base_confidence))

        # Determine discovery depth
        if refs_with_detail >= max(3, total_refs * 0.6):
            depth = "deep"
        elif refs_with_detail >= 1:
            depth = "medium"
        else:
            depth = "shallow"

        # Enriched sources
        enriched = []
        for ref in key_references[:15]:
            doi_clean = ref.replace("DOI:", "").replace("doi:", "").strip()
            art = next((a for a in evidence.all_articles if a["doi"] == doi_clean), None)
            if art:
                enriched.append({
                    "doi": doi_clean,
                    "title_ru": art["title_ru"] or art["title"],
                    "source": art["source"],
                    "year": art["year"],
                })

        status = "duplicate" if is_duplicate else "proposed"

        return ArticleProposal(
            id=f"prop_{_now_iso().replace('-','').replace(':','').replace('.','')}_{index}",
            title=raw.get("title", "[без заголовка]"),
            thesis=raw.get("thesis", "[без тезиса]"),
            target_audience=raw.get("target_audience", "general_public"),
            confidence=base_confidence,
            sources_available=len(key_references),
            sources_needed=int(raw.get("sources_needed", 5)),
            key_references=key_references,
            gap_filled=raw.get("gap_filled", ""),
            estimated_sections=raw.get("estimated_sections", []),
            status=status,
            enriched_sources=enriched,
            graph_roles={},  # Filled by orchestrator's _enrich_with_graph
            discovery_depth=depth,
        )

    # ── Checkpoint / Resume helpers ─────────────────────────────────

    def _save_checkpoint(self, state: EditorState) -> None:
        path = self.jobs_dir / f"{state.job_id}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(state.to_dict(), f, ensure_ascii=False, indent=2, default=str)
        logger.debug("[editor] Checkpoint saved: %s", path)

    def _reconstruct_result(self, state_data: dict) -> EditorResult:
        """Reconstruct EditorResult from saved checkpoint."""
        discovery = None
        dd = state_data.get("discovery") or state_data.get("analysis")
        if dd:
            discovery = DiscoveryReport(**{k: v for k, v in dd.items()
                                          if k in DiscoveryReport.__dataclass_fields__})

        proposals = []
        for pd in state_data.get("proposals", []):
            proposals.append(ArticleProposal(**pd))

        return EditorResult(
            job_id=state_data["job_id"],
            topic=state_data.get("topic", ""),
            status=state_data.get("phase", "unknown"),
            analysis=dd,
            discovery=discovery,
            proposals=proposals,
            error=state_data.get("error"),
        )

    # ── Helpers ────────────────────────────────────────────────────

    @staticmethod
    def _gen_job_id() -> str:
        return f"edit_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"

    def _check_doi_exists(self, doi: str) -> bool:
        if self.tools is None:
            return False
        result = self.tools.execute("validate_doi", {"doi": doi})
        if hasattr(result, 'success'):
            return result.success and result.data.get("valid", False)
        try:
            d = json.loads(result) if isinstance(result, str) else result
            return d.get("valid", False)
        except Exception:
            return False

    @staticmethod
    def _extract_gaps(text: str) -> list[str]:
        gaps = []
        patterns = [
            r'(?:пробел|не хватает|недостаточно|gap|missing)[^.:]*[:\.]\s*([^\n]+)',
            r'-\s*(?:нет|отсутствует|не покрыто)[^\n]*',
        ]
        for pattern in patterns:
            for m in re.finditer(pattern, text, re.IGNORECASE):
                gap = m.group(1) if m.lastindex else m.group(0)
                gap = gap.strip().lstrip("- ").strip()
                if len(gap) > 5:
                    gaps.append(gap)
        return gaps[:10]

    @staticmethod
    def _similarity(a: str, b: str) -> float:
        if not a or not b:
            return 0.0
        sa = set(a.lower().split())
        sb = set(b.lower().split())
        intersection = sa & sb
        union = sa | sb
        return len(intersection) / len(union) if union else 0.0


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()
